### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by greg0ire**
I tried your library, it was cool. I proceeded to create symfony2 services to use it inside a symfony2 project. Then I noticed there already was bundle! Let us add something about it!

### CODE REVIEW

**Comment by greg0ire** [comment]
ping @touki653

**Comment by touki653** [comment]
As I stated in [FTPBundle/#1](https://github.com/touki653/FTPBundle/issues/1) this library is in DEV mode since it doesn't support all functionnalities of the wrapper. Moreover, I'm working (when I give myself some time) on a version 2.0. For these reasons I'd rather not to advertise an unstable library

**Comment by greg0ire** [comment]
Fair enough, I remove the commit you don't want.

**Comment by touki653** [comment]
Thanks!

**Pull request merged**
